# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SZQRCodeViewController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
  # Pods for SZQRCodeViewController

  target 'SZQRCodeViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SZQRCodeViewControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
